version: "3.7"
services:
  rust:
    build:
      context: docker/rust
      target: ${ENVIRONMENT:-production-pseudo}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    working_dir: /app
    volumes:
      - .:/app

  mongo:
    build:
      context: docker/mongo
      target: ${ENVIRONMENT:-production-pseudo}
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    volumes:
      - .:/app

